# Site settings
title: Elite Aircraft Interiors
email: arturo@eliteaircraftinteriors.net
address: 240 SW 34th Street, Fort Lauderdale, FL 33315
description: blah blah blah
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eliteaircraft.github.io" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
